export const types = {
    authLogin: '[auth] Login User',
    authLoginGit: '[auth] GitHub Login',
    clearAuthLogin: '[auth] Clear Auth Login',
    login: '[login] Login',
    infoToken: '[info] Info Token',

    gitHubInactivateLogOut: '[auth] Logout Github Inactivated User',
    requestInProgress: '[request] Request In Progress',
    requestFinished: '[request] Request Finished',
    requestCleaned: '[request] Request Cleaned',

    responseFinished: '[response] Response Finished',
    responseCleaned: '[response] Response Cleaned',

    getListStudents: '[student] Get List Students',
    studentRegister: '[student] Register Student',
    studentGetInfo: '[student] Get Info Student',
    studentUpdateInfo: '[student] Update Info Student',
    studentSearch: '[student] Search Company', //-VERIFICAR-//
    addStudentToProject: '[student] Add student to project',
    unApplyStudent: '[student] Un Applu student to project',
    deleteOrInactiveStudent: '[student] inactive student to data base',
    updateMail:"[student] update mail", 

    registerCompany: '[company] Register Company',
    companyGetInfo: '[company] Get info company',
    companyUpdateInfo: '[company] Update info company',
    companySearch: '[company] Serch Company', //-VERIFICAR-//
    acceptStudent: '[Company] Student Accept',
    deleteStudent: '[Company] Student delete',
    companyGetList: '[Company] Get list Company',
    deleteCompany: '[Company] Company delete',
    disableCompany: '[Company] disable Company',
    ratingProjectCompany: '[Company] rating Project', //toy provando
    ratingProject: '[Company] rating CompanyProject',
    clearCompany: '[Company] clear get company',
    getCountries: '[Company] get countries',
    detailCompany: '[Company] Detail Company',
    inProggres:"[company] in proggres project",//prueva

    newProject: '[project] Create New Project',
    getProjects: '[project] Get Projects',
    projectsFilter: '[projects], get filtered projects',
    getProjectById: '[project] Get Project By Id',
    getCategory: '[project] Get Category',
    getMyProjectCompany: '[project]  Get My Project Company',
    filters: '[project] Filters',
    clearProject: '[project] Clear Projects',

    showError: '[error] Show Error',
    clearError: '[error] Clear Error',
    getAllProjects: '[project] get all Project',
    AdminAprovedProject: '[admin]project aproved',
    AdminEliminatedProject:
        '[admin]admin eliminated project and send email for why',
    adminGetCharts: '[admin] admin get charts',
    getAdmins: '[admin] get all admins',
    getInfoAdmin: '[admin] get info admin',
    registerAdmin: '[admin] Register Admin',
    getAllReviews: '[admin] get all reviews',
    setState: '[admin] set state if project | student | company',
    setReclutamientoinProject: '[admin] set reclutamiento in project',
    adminEliminatedCompany: '[admin]admin eliminated company and send email',
    multipleSwitchAlumno: '[admin]switch state alumno dashAdmin',
    filterReview: '[admin]filter review',
    AdminEliminatedReview: '[admin delete review',
    clearAdmin: '[admin] clear state',
    disableAdmin: '[admin] disable admin',
};
